artifact_location: file:///C:/Users/DELL/Desktop/Ai/ai-sales-forecaster/mlruns_local/904236849272010536
creation_time: 1759785735670
experiment_id: '904236849272010536'
last_update_time: 1759785735670
lifecycle_stage: active
name: AI_Sales_Forecaster
