name: Sales Forecaster CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Data Preprocessing
      run: |
        python src/data_preprocessing.py

    - name: Train the Model
      run: |
        python src/train.py

    - name: Evaluate the Model
      run: |
        python src/evaluate.py

    - name: Run Unit Tests (optional)
      run: |
        pytest tests/ --maxfail=1 --disable-warnings -q

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy FastAPI App
        run: echo " Deployment step goes here (e.g. to Render, Azure, or EC2)"
